package ru.svyaznoybank.handbook.jpa.domain;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.SequenceGenerator;

/**
 * Base calss for non-dictionary entites. ID generated by sequence.
 * @author Roman Zaripov
 */
@MappedSuperclass
@AttributeOverrides({
	@AttributeOverride(name = "creator", column = @Column(name = "CREATE_USER")),
	@AttributeOverride(name = "updater", column = @Column(name = "UPDATE_USER"))
})
@SequenceGenerator(name = AbstractIdentity.SEQ_NAME, sequenceName = "ID", allocationSize = 1)
public abstract class AbstractIdentity extends AuditEntity implements Identity {

	public static final String SEQ_NAME = "sequence";
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQ_NAME)
	@Column(name = "ID")
	private Long id;

	// --- Getters / Setters ---
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
}